In [1]:
import pandas as pd

In [2]:
# read file first
file_path = r"C:\Users\Admin\Desktop\Grocery Store Analytics\Data Set\Cleaned data\sales_cleaned.csv"

# Load and view the data
sales = pd.read_csv(file_path)
sales.head()

,Order_ID,Order_Date,Customer_ID,Product_ID,Store_ID,Quantity,Unit_Price,Unit_Cost,Discount_Percent,Gross_Sales,...,Profit,Payment_Method,Product_Name,Category,Customer_Name,City,Age_Group,Member_Type,Store_Name,Store_Type
0,ORD00001,2024-11-06,C0240,P035,S004,1,300,150,5,300,...,135.0,Credit Card,Bucket,Cleaning & Household,Arjun Joshi,Hyderabad,55+,Regular,FreshMart Hyderabad,Supermarket
1,ORD00002,2024-05-07,C0082,P041,S001,2,30,20,5,60,...,17.0,Credit Card,Salt 1kg,Groceries & Food,Karan Kumar,Delhi,45-54,Regular,FreshMart Delhi Central,Supermarket
2,ORD00003,2026-09-06,C0044,P096,S003,2,500,260,0,1000,...,480.0,UPI,Desk Organizer,Home & Living,Rohan Mehta,Bengaluru,35-44,Regular,FreshMart Bengaluru Hub,Hypermarket
3,ORD00004,2025-12-02,C0066,P096,S007,2,500,260,15,1000,...,330.0,Debit Card,Desk Organizer,Home & Living,Vivaan Verma,Kolkata,35-44,Regular,FreshMart Kolkata,Supermarket
4,ORD00005,2025-06-25,C0365,P067,S006,2,450,280,0,900,...,340.0,UPI,Moisturizer,Personal Care,Ananya Singh,Pune,55+,Gold,FreshMart Pune,Supermarket

In [5]:
df = sales

In [6]:
df.head()

,Order_ID,Order_Date,Customer_ID,Product_ID,Store_ID,Quantity,Unit_Price,Unit_Cost,Discount_Percent,Gross_Sales,...,Profit,Payment_Method,Product_Name,Category,Customer_Name,City,Age_Group,Member_Type,Store_Name,Store_Type
0,ORD00001,2024-11-06,C0240,P035,S004,1,300,150,5,300,...,135.0,Credit Card,Bucket,Cleaning & Household,Arjun Joshi,Hyderabad,55+,Regular,FreshMart Hyderabad,Supermarket
1,ORD00002,2024-05-07,C0082,P041,S001,2,30,20,5,60,...,17.0,Credit Card,Salt 1kg,Groceries & Food,Karan Kumar,Delhi,45-54,Regular,FreshMart Delhi Central,Supermarket
2,ORD00003,2026-09-06,C0044,P096,S003,2,500,260,0,1000,...,480.0,UPI,Desk Organizer,Home & Living,Rohan Mehta,Bengaluru,35-44,Regular,FreshMart Bengaluru Hub,Hypermarket
3,ORD00004,2025-12-02,C0066,P096,S007,2,500,260,15,1000,...,330.0,Debit Card,Desk Organizer,Home & Living,Vivaan Verma,Kolkata,35-44,Regular,FreshMart Kolkata,Supermarket
4,ORD00005,2025-06-25,C0365,P067,S006,2,450,280,0,900,...,340.0,UPI,Moisturizer,Personal Care,Ananya Singh,Pune,55+,Gold,FreshMart Pune,Supermarket

In [7]:
# Created product data
products = df[
    [
        "Product_ID",
        "Product_Name",
        "Category",
        "Unit_Price",
        "Unit_Cost"
    ]
].drop_duplicates()

products_output_path = r"C:\Users\Admin\Desktop\Grocery Store Analytics\Data Set\products.csv"

products.to_csv(products_output_path, index=False)

# 4. View the first few rows
products.head()

  Product_ID      Product_Name              Category  Unit_Price  Unit_Cost
0       P035            Bucket  Cleaning & Household         300        150
1       P041          Salt 1kg      Groceries & Food          30         20
2       P096    Desk Organizer         Home & Living         500        260
4       P067       Moisturizer         Personal Care         450        280
5       P043  Breakfast Cereal      Groceries & Food         280        170

In [8]:
# craeted customer data
customers = df[
    [
        "Customer_ID",
        "Customer_Name",
        "City",
        "Age_Group",
        "Member_Type"
    ]
].drop_duplicates()

customers_output_path = r"C:\Users\Admin\Desktop\Grocery Store Analytics\Data Set\customers.csv"

customers.to_csv(customers_output_path, index=False)

# 4. View the first few rows
customers.head()

  Customer_ID Customer_Name       City Age_Group Member_Type
0       C0240   Arjun Joshi  Hyderabad       55+     Regular
1       C0082   Karan Kumar      Delhi     45-54     Regular
2       C0044   Rohan Mehta  Bengaluru     35-44     Regular
3       C0066  Vivaan Verma    Kolkata     35-44     Regular
4       C0365  Ananya Singh       Pune       55+        Gold

In [10]:
# created store data
stores = df[
    [
        "Store_ID",
        "Store_Name",
        "City",
        "Store_Type"
    ]
].drop_duplicates()

store_output_path = r"C:\Users\Admin\Desktop\Grocery Store Analytics\Data Set\store.csv"

stores.to_csv(store_output_path, index=False)

stores.head()

  Store_ID               Store_Name       City   Store_Type
0     S004      FreshMart Hyderabad  Hyderabad  Supermarket
1     S001  FreshMart Delhi Central      Delhi  Supermarket
2     S003  FreshMart Bengaluru Hub  Bengaluru  Hypermarket
3     S007        FreshMart Kolkata    Kolkata  Supermarket
4     S006           FreshMart Pune       Pune  Supermarket

In [11]:
# Created sales data
sales = df[
    [
        "Order_ID",
        "Order_Date",
        "Customer_ID",
        "Product_ID",
        "Store_ID",
        "Quantity",
        "Discount_Percent",
        "Gross_Sales",
        "Discount_Amount",
        "Revenue",
        "Profit",
        "Payment_Method"
    ]
]

sales_output_path = r"C:\Users\Admin\Desktop\Grocery Store Analytics\Data Set\sales.csv"

sales.to_csv(sales_output_path, index=False)

# 4. View the first few rows
sales.head()

,Order_ID,Order_Date,Customer_ID,Product_ID,Store_ID,Quantity,Discount_Percent,Gross_Sales,Discount_Amount,Revenue,Profit,Payment_Method
0,ORD00001,2024-11-06,C0240,P035,S004,1,5,300,15.0,285.0,135.0,Credit Card
1,ORD00002,2024-05-07,C0082,P041,S001,2,5,60,3.0,57.0,17.0,Credit Card
2,ORD00003,2026-09-06,C0044,P096,S003,2,0,1000,0.0,1000.0,480.0,UPI
3,ORD00004,2025-12-02,C0066,P096,S007,2,15,1000,150.0,850.0,330.0,Debit Card
4,ORD00005,2025-06-25,C0365,P067,S006,2,0,900,0.0,900.0,340.0,UPI

In [12]:
print("Products:", products.shape)
print("Customers:", customers.shape)
print("Stores:", stores.shape)
print("Sales:", sales.shape)

Products: (96, 5)
Customers: (400, 5)
Stores: (8, 4)
Sales: (3000, 12)